load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "toolchains_bzl",
    srcs = ["sh_toolchain.bzl"],
    visibility = ["//visibility:public"],
)

exports_files(
    ["sh_toolchain.bzl"],
    visibility = ["//visibility:public"],
)
